/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class HudFastPathEvent implements org.apache.thrift.TBase<HudFastPathEvent, HudFastPathEvent._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HudFastPathEvent");

  private static final org.apache.thrift.protocol.TField FP_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("fpData", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new HudFastPathEventStandardSchemeFactory());
    schemes.put(TupleScheme.class, new HudFastPathEventTupleSchemeFactory());
  }

  public String fpData; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FP_DATA((short)1, "fpData");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FP_DATA
          return FP_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FP_DATA, new org.apache.thrift.meta_data.FieldMetaData("fpData", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HudFastPathEvent.class, metaDataMap);
  }

  public HudFastPathEvent() {
  }

  public HudFastPathEvent(
    String fpData)
  {
    this();
    this.fpData = fpData;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HudFastPathEvent(HudFastPathEvent other) {
    if (other.isSetFpData()) {
      this.fpData = other.fpData;
    }
  }

  public HudFastPathEvent deepCopy() {
    return new HudFastPathEvent(this);
  }

  @Override
  public void clear() {
    this.fpData = null;
  }

  public String getFpData() {
    return this.fpData;
  }

  public HudFastPathEvent setFpData(String fpData) {
    this.fpData = fpData;
    return this;
  }

  public void unsetFpData() {
    this.fpData = null;
  }

  /** Returns true if field fpData is set (has been assigned a value) and false otherwise */
  public boolean isSetFpData() {
    return this.fpData != null;
  }

  public void setFpDataIsSet(boolean value) {
    if (!value) {
      this.fpData = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FP_DATA:
      if (value == null) {
        unsetFpData();
      } else {
        setFpData((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FP_DATA:
      return getFpData();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FP_DATA:
      return isSetFpData();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HudFastPathEvent)
      return this.equals((HudFastPathEvent)that);
    return false;
  }

  public boolean equals(HudFastPathEvent that) {
    if (that == null)
      return false;

    boolean this_present_fpData = true && this.isSetFpData();
    boolean that_present_fpData = true && that.isSetFpData();
    if (this_present_fpData || that_present_fpData) {
      if (!(this_present_fpData && that_present_fpData))
        return false;
      if (!this.fpData.equals(that.fpData))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(HudFastPathEvent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    HudFastPathEvent typedOther = (HudFastPathEvent)other;

    lastComparison = Boolean.valueOf(isSetFpData()).compareTo(typedOther.isSetFpData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFpData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fpData, typedOther.fpData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HudFastPathEvent(");
    boolean first = true;

    sb.append("fpData:");
    if (this.fpData == null) {
      sb.append("null");
    } else {
      sb.append(this.fpData);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class HudFastPathEventStandardSchemeFactory implements SchemeFactory {
    public HudFastPathEventStandardScheme getScheme() {
      return new HudFastPathEventStandardScheme();
    }
  }

  private static class HudFastPathEventStandardScheme extends StandardScheme<HudFastPathEvent> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, HudFastPathEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FP_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.fpData = iprot.readString();
              struct.setFpDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, HudFastPathEvent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.fpData != null) {
        oprot.writeFieldBegin(FP_DATA_FIELD_DESC);
        oprot.writeString(struct.fpData);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class HudFastPathEventTupleSchemeFactory implements SchemeFactory {
    public HudFastPathEventTupleScheme getScheme() {
      return new HudFastPathEventTupleScheme();
    }
  }

  private static class HudFastPathEventTupleScheme extends TupleScheme<HudFastPathEvent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, HudFastPathEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFpData()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetFpData()) {
        oprot.writeString(struct.fpData);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, HudFastPathEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.fpData = iprot.readString();
        struct.setFpDataIsSet(true);
      }
    }
  }

}

