/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class HudPIQLService {

  public interface Iface {

    public HudPIQLResponse executePIQLQuery(HudPIQLQuery piqlEvent) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void executePIQLQuery(HudPIQLQuery piqlEvent, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.executePIQLQuery_call> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public HudPIQLResponse executePIQLQuery(HudPIQLQuery piqlEvent) throws org.apache.thrift.TException
    {
      send_executePIQLQuery(piqlEvent);
      return recv_executePIQLQuery();
    }

    public void send_executePIQLQuery(HudPIQLQuery piqlEvent) throws org.apache.thrift.TException
    {
      executePIQLQuery_args args = new executePIQLQuery_args();
      args.setPiqlEvent(piqlEvent);
      sendBase("executePIQLQuery", args);
    }

    public HudPIQLResponse recv_executePIQLQuery() throws org.apache.thrift.TException
    {
      executePIQLQuery_result result = new executePIQLQuery_result();
      receiveBase(result, "executePIQLQuery");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "executePIQLQuery failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void executePIQLQuery(HudPIQLQuery piqlEvent, org.apache.thrift.async.AsyncMethodCallback<executePIQLQuery_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      executePIQLQuery_call method_call = new executePIQLQuery_call(piqlEvent, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class executePIQLQuery_call extends org.apache.thrift.async.TAsyncMethodCall {
      private HudPIQLQuery piqlEvent;
      public executePIQLQuery_call(HudPIQLQuery piqlEvent, org.apache.thrift.async.AsyncMethodCallback<executePIQLQuery_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.piqlEvent = piqlEvent;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("executePIQLQuery", org.apache.thrift.protocol.TMessageType.CALL, 0));
        executePIQLQuery_args args = new executePIQLQuery_args();
        args.setPiqlEvent(piqlEvent);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public HudPIQLResponse getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_executePIQLQuery();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("executePIQLQuery", new executePIQLQuery());
      return processMap;
    }

    public static class executePIQLQuery<I extends Iface> extends org.apache.thrift.ProcessFunction<I, executePIQLQuery_args> {
      public executePIQLQuery() {
        super("executePIQLQuery");
      }

      public executePIQLQuery_args getEmptyArgsInstance() {
        return new executePIQLQuery_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public executePIQLQuery_result getResult(I iface, executePIQLQuery_args args) throws org.apache.thrift.TException {
        executePIQLQuery_result result = new executePIQLQuery_result();
        result.success = iface.executePIQLQuery(args.piqlEvent);
        return result;
      }
    }

  }

  public static class executePIQLQuery_args implements org.apache.thrift.TBase<executePIQLQuery_args, executePIQLQuery_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("executePIQLQuery_args");

    private static final org.apache.thrift.protocol.TField PIQL_EVENT_FIELD_DESC = new org.apache.thrift.protocol.TField("piqlEvent", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new executePIQLQuery_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new executePIQLQuery_argsTupleSchemeFactory());
    }

    public HudPIQLQuery piqlEvent; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      PIQL_EVENT((short)1, "piqlEvent");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // PIQL_EVENT
            return PIQL_EVENT;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.PIQL_EVENT, new org.apache.thrift.meta_data.FieldMetaData("piqlEvent", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, HudPIQLQuery.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(executePIQLQuery_args.class, metaDataMap);
    }

    public executePIQLQuery_args() {
    }

    public executePIQLQuery_args(
      HudPIQLQuery piqlEvent)
    {
      this();
      this.piqlEvent = piqlEvent;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public executePIQLQuery_args(executePIQLQuery_args other) {
      if (other.isSetPiqlEvent()) {
        this.piqlEvent = new HudPIQLQuery(other.piqlEvent);
      }
    }

    public executePIQLQuery_args deepCopy() {
      return new executePIQLQuery_args(this);
    }

    @Override
    public void clear() {
      this.piqlEvent = null;
    }

    public HudPIQLQuery getPiqlEvent() {
      return this.piqlEvent;
    }

    public executePIQLQuery_args setPiqlEvent(HudPIQLQuery piqlEvent) {
      this.piqlEvent = piqlEvent;
      return this;
    }

    public void unsetPiqlEvent() {
      this.piqlEvent = null;
    }

    /** Returns true if field piqlEvent is set (has been assigned a value) and false otherwise */
    public boolean isSetPiqlEvent() {
      return this.piqlEvent != null;
    }

    public void setPiqlEventIsSet(boolean value) {
      if (!value) {
        this.piqlEvent = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case PIQL_EVENT:
        if (value == null) {
          unsetPiqlEvent();
        } else {
          setPiqlEvent((HudPIQLQuery)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case PIQL_EVENT:
        return getPiqlEvent();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case PIQL_EVENT:
        return isSetPiqlEvent();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof executePIQLQuery_args)
        return this.equals((executePIQLQuery_args)that);
      return false;
    }

    public boolean equals(executePIQLQuery_args that) {
      if (that == null)
        return false;

      boolean this_present_piqlEvent = true && this.isSetPiqlEvent();
      boolean that_present_piqlEvent = true && that.isSetPiqlEvent();
      if (this_present_piqlEvent || that_present_piqlEvent) {
        if (!(this_present_piqlEvent && that_present_piqlEvent))
          return false;
        if (!this.piqlEvent.equals(that.piqlEvent))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(executePIQLQuery_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      executePIQLQuery_args typedOther = (executePIQLQuery_args)other;

      lastComparison = Boolean.valueOf(isSetPiqlEvent()).compareTo(typedOther.isSetPiqlEvent());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetPiqlEvent()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.piqlEvent, typedOther.piqlEvent);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("executePIQLQuery_args(");
      boolean first = true;

      sb.append("piqlEvent:");
      if (this.piqlEvent == null) {
        sb.append("null");
      } else {
        sb.append(this.piqlEvent);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (piqlEvent != null) {
        piqlEvent.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class executePIQLQuery_argsStandardSchemeFactory implements SchemeFactory {
      public executePIQLQuery_argsStandardScheme getScheme() {
        return new executePIQLQuery_argsStandardScheme();
      }
    }

    private static class executePIQLQuery_argsStandardScheme extends StandardScheme<executePIQLQuery_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, executePIQLQuery_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // PIQL_EVENT
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.piqlEvent = new HudPIQLQuery();
                struct.piqlEvent.read(iprot);
                struct.setPiqlEventIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, executePIQLQuery_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.piqlEvent != null) {
          oprot.writeFieldBegin(PIQL_EVENT_FIELD_DESC);
          struct.piqlEvent.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class executePIQLQuery_argsTupleSchemeFactory implements SchemeFactory {
      public executePIQLQuery_argsTupleScheme getScheme() {
        return new executePIQLQuery_argsTupleScheme();
      }
    }

    private static class executePIQLQuery_argsTupleScheme extends TupleScheme<executePIQLQuery_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, executePIQLQuery_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetPiqlEvent()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetPiqlEvent()) {
          struct.piqlEvent.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, executePIQLQuery_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.piqlEvent = new HudPIQLQuery();
          struct.piqlEvent.read(iprot);
          struct.setPiqlEventIsSet(true);
        }
      }
    }

  }

  public static class executePIQLQuery_result implements org.apache.thrift.TBase<executePIQLQuery_result, executePIQLQuery_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("executePIQLQuery_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new executePIQLQuery_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new executePIQLQuery_resultTupleSchemeFactory());
    }

    public HudPIQLResponse success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, HudPIQLResponse.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(executePIQLQuery_result.class, metaDataMap);
    }

    public executePIQLQuery_result() {
    }

    public executePIQLQuery_result(
      HudPIQLResponse success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public executePIQLQuery_result(executePIQLQuery_result other) {
      if (other.isSetSuccess()) {
        this.success = new HudPIQLResponse(other.success);
      }
    }

    public executePIQLQuery_result deepCopy() {
      return new executePIQLQuery_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public HudPIQLResponse getSuccess() {
      return this.success;
    }

    public executePIQLQuery_result setSuccess(HudPIQLResponse success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((HudPIQLResponse)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof executePIQLQuery_result)
        return this.equals((executePIQLQuery_result)that);
      return false;
    }

    public boolean equals(executePIQLQuery_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(executePIQLQuery_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      executePIQLQuery_result typedOther = (executePIQLQuery_result)other;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("executePIQLQuery_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (success != null) {
        success.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class executePIQLQuery_resultStandardSchemeFactory implements SchemeFactory {
      public executePIQLQuery_resultStandardScheme getScheme() {
        return new executePIQLQuery_resultStandardScheme();
      }
    }

    private static class executePIQLQuery_resultStandardScheme extends StandardScheme<executePIQLQuery_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, executePIQLQuery_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new HudPIQLResponse();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, executePIQLQuery_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class executePIQLQuery_resultTupleSchemeFactory implements SchemeFactory {
      public executePIQLQuery_resultTupleScheme getScheme() {
        return new executePIQLQuery_resultTupleScheme();
      }
    }

    private static class executePIQLQuery_resultTupleScheme extends TupleScheme<executePIQLQuery_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, executePIQLQuery_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, executePIQLQuery_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = new HudPIQLResponse();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
