/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ThriftJobList implements org.apache.thrift.TBase<ThriftJobList, ThriftJobList._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftJobList");

  private static final org.apache.thrift.protocol.TField JOB_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("jobList", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ThriftJobListStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ThriftJobListTupleSchemeFactory());
  }

  public String jobList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    JOB_LIST((short)1, "jobList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // JOB_LIST
          return JOB_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.JOB_LIST, new org.apache.thrift.meta_data.FieldMetaData("jobList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftJobList.class, metaDataMap);
  }

  public ThriftJobList() {
  }

  public ThriftJobList(
    String jobList)
  {
    this();
    this.jobList = jobList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftJobList(ThriftJobList other) {
    if (other.isSetJobList()) {
      this.jobList = other.jobList;
    }
  }

  public ThriftJobList deepCopy() {
    return new ThriftJobList(this);
  }

  @Override
  public void clear() {
    this.jobList = null;
  }

  public String getJobList() {
    return this.jobList;
  }

  public ThriftJobList setJobList(String jobList) {
    this.jobList = jobList;
    return this;
  }

  public void unsetJobList() {
    this.jobList = null;
  }

  /** Returns true if field jobList is set (has been assigned a value) and false otherwise */
  public boolean isSetJobList() {
    return this.jobList != null;
  }

  public void setJobListIsSet(boolean value) {
    if (!value) {
      this.jobList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case JOB_LIST:
      if (value == null) {
        unsetJobList();
      } else {
        setJobList((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case JOB_LIST:
      return getJobList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case JOB_LIST:
      return isSetJobList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ThriftJobList)
      return this.equals((ThriftJobList)that);
    return false;
  }

  public boolean equals(ThriftJobList that) {
    if (that == null)
      return false;

    boolean this_present_jobList = true && this.isSetJobList();
    boolean that_present_jobList = true && that.isSetJobList();
    if (this_present_jobList || that_present_jobList) {
      if (!(this_present_jobList && that_present_jobList))
        return false;
      if (!this.jobList.equals(that.jobList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(ThriftJobList other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    ThriftJobList typedOther = (ThriftJobList)other;

    lastComparison = Boolean.valueOf(isSetJobList()).compareTo(typedOther.isSetJobList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJobList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.jobList, typedOther.jobList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ThriftJobList(");
    boolean first = true;

    sb.append("jobList:");
    if (this.jobList == null) {
      sb.append("null");
    } else {
      sb.append(this.jobList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftJobListStandardSchemeFactory implements SchemeFactory {
    public ThriftJobListStandardScheme getScheme() {
      return new ThriftJobListStandardScheme();
    }
  }

  private static class ThriftJobListStandardScheme extends StandardScheme<ThriftJobList> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftJobList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // JOB_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.jobList = iprot.readString();
              struct.setJobListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftJobList struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.jobList != null) {
        oprot.writeFieldBegin(JOB_LIST_FIELD_DESC);
        oprot.writeString(struct.jobList);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftJobListTupleSchemeFactory implements SchemeFactory {
    public ThriftJobListTupleScheme getScheme() {
      return new ThriftJobListTupleScheme();
    }
  }

  private static class ThriftJobListTupleScheme extends TupleScheme<ThriftJobList> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftJobList struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetJobList()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetJobList()) {
        oprot.writeString(struct.jobList);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftJobList struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.jobList = iprot.readString();
        struct.setJobListIsSet(true);
      }
    }
  }

}

