//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

HudFastPathEvent = function(args) {
  this.fpData = null;
  if (args) {
    if (args.fpData !== undefined) {
      this.fpData = args.fpData;
    }
  }
};
HudFastPathEvent.prototype = {};
HudFastPathEvent.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.fpData = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HudFastPathEvent.prototype.write = function(output) {
  output.writeStructBegin('HudFastPathEvent');
  if (this.fpData !== null && this.fpData !== undefined) {
    output.writeFieldBegin('fpData', Thrift.Type.STRING, 1);
    output.writeString(this.fpData);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

