//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

HudFastPathService_executeFastPath_args = function(args) {
  this.event = null;
  if (args) {
    if (args.event !== undefined) {
      this.event = args.event;
    }
  }
};
HudFastPathService_executeFastPath_args.prototype = {};
HudFastPathService_executeFastPath_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.event = new HudFastPathEvent();
        this.event.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HudFastPathService_executeFastPath_args.prototype.write = function(output) {
  output.writeStructBegin('HudFastPathService_executeFastPath_args');
  if (this.event !== null && this.event !== undefined) {
    output.writeFieldBegin('event', Thrift.Type.STRUCT, 1);
    this.event.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HudFastPathService_executeFastPath_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
HudFastPathService_executeFastPath_result.prototype = {};
HudFastPathService_executeFastPath_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new HudFastPathEvent();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HudFastPathService_executeFastPath_result.prototype.write = function(output) {
  output.writeStructBegin('HudFastPathService_executeFastPath_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HudFastPathServiceClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
HudFastPathServiceClient.prototype = {};
HudFastPathServiceClient.prototype.executeFastPath = function(event) {
  this.send_executeFastPath(event);
  return this.recv_executeFastPath();
};

HudFastPathServiceClient.prototype.send_executeFastPath = function(event) {
  this.output.writeMessageBegin('executeFastPath', Thrift.MessageType.CALL, this.seqid);
  var args = new HudFastPathService_executeFastPath_args();
  args.event = event;
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush();
};

HudFastPathServiceClient.prototype.recv_executeFastPath = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new HudFastPathService_executeFastPath_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'executeFastPath failed: unknown result';
};
